### ISSUE TITLE
Add management of k8s clouds

### ISSUE THREAD

**Issue by jsimpso** [juju/terraform-provider-juju#232]
Hi,

This is a wishlist item to request the ability to manage k8s clouds ([juju add-k8s](https://juju.is/docs/olm/juju-add-k8s), [juju remove-k8s](https://juju.is/docs/olm/juju-remove-k8s)).

I've opened this knowing that #105 exists (Ability to manage clouds) as I'm not sure how much is shared between `add-cloud` and `add-k8s`.

Thanks :)

**Comment by gruyaume** [comment]
+1 on this item, currently one needs to go back and forth between Terraform and Juju CLI:
1. Create K8s cluster (Terraform)
1. Bootstrap juju controller (manual)
3. Add K8s cluster to Juju controller (manual)
4. Deploy application on k8s cloud (Terraform)

**Comment by nishant-dash** [comment]
+1 from me as well, I have a similar workflow I am personally working on and having this resource in terraform would be great!

**Comment by tlm** [comment]
Just providing an update onto this. We received a ping about this on Matrix today. Essentially what we are looking to add here is the ability to model a cloud in terraform so that the existing credential aspects can be used. This would all use our AddCloud facades. AddK8s is just a special client command and doesn't have any special translation to the server facades.

**Comment by hmlanigan** [comment]
@tlm you can specify a model should use a specific cloud today, not sure why its not working for k8s.

**Comment by tlm** [comment]
@hmlanigan What they are after is the ability to provision a Kubernetes cloud through Terraform into their respective environments then add that newly created cloud to Juju.

Because Kubernetes isn't at a fixed location like the other clouds we need a call to AddCloud to happen to tell the controller about it then they can provide credentials.

**Comment by dparv** [comment]
+1!

**Comment by hmlanigan** [comment]
We need to implement a cloud resource in general. There is a Jira epic with many updates related to clouds which hasn't received a high enough priority yet to start work.

We do gladly accept contributes and there is a process for getting schema changes and additions approved.

**Comment by anvial** [comment]
The feature is now part of the TF provider: https://registry.terraform.io/providers/juju/juju/latest/docs/resources/kubernetes_cloud
