### ISSUE TITLE
Race condition creating model and application

### ISSUE THREAD

**Issue by mthaddon** [juju/terraform-provider-juju#345]
### Description

There seems to be a race condition if creating a model and an application

### Urgency

Casually reporting

### Terraform Juju Provider version

0.10.0

### Terraform version

v1.5.7

### Terraform Configuration(s)

```terraform
terraform {
  required_version = ">= 1.5"
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "0.10.0"
    }
  }
}
provider "juju" {}

resource "juju_model" "tf_test" {
  name = "tf-test"
}

resource "juju_application" "ubuntu" {
  name  = "ubuntu"
  model = "tf-test"

  charm {
    name = "ubuntu"
  }

  units = 1
}
```

### Reproduce / Test

```shell
When running `terraform apply` of the above against an empty machine controller I got this: https://pastebin.ubuntu.com/p/TVRxHhvqym/
```

**Comment by cderici** [comment]
@mthaddon so the reason this is happening is that you wrote in the config for `juju_application` resource the name of the model as `model = "tf-test"` instead of `model = juju_model.tf_test.name`, which would've had the terraform engine to create a dependency between the resources and communicate that nicely to the juju provider.

We're not entirely sure what's the conventional way to handle this in the terraform world (i.e. is it reasonable to expect the plan writers to always write it in that way?), which is why we're keeping this issue open to get more insight.

**Comment by gboutry** [comment]
From my experience, it's expected that you would write references to other resources if your current resource has a dependency.

If submitted plan works, it's luck, if it fails, it's expected.

(when you can't clearly use a reference to another resource, you can use `depends_on`, but it's not needed in this case)
