### ISSUE TITLE
Add application space support

### ISSUE THREAD

**Issue by gboutry** [juju/terraform-provider-juju#400]
### Type of change

Changing existing schema

### Description

```terraform
I plan to implement the equivalent to following commands to the provider:

`juju deploy <myapp> --bind <a space>` # makes space default space on new application
`juju bind <myapp> <a space>` # makes space default space on an existing application
`juju bind <myapp> <endpoint-1>=<a space>` # changes relation's bound space
```

#### application schema:
```go
"default-space": schema.StringAttribute{
	Description: "Configure default endpoints bindings",
	Optional:    true,
	Computed:    true,
	PlanModifiers: []planmodifier.String{
		stringplanmodifier.UseStateForUnknown(),
	},
},
```

#### integration schema:
```go
"space": schema.StringAttribute{
	Description: "Name of the space this integration will be bound to.",
	Optional:    true,
	Computed:    true,
	PlanModifiers: []planmodifier.String{
		stringplanmodifier.UseStateForUnknown(),
	},
},
```

### Notes & References

This change is related to #336 but I believe it does not depend on it. Thus, it can be worked separately.

I want to set fields to Optional + Computed because they are not needed by default, and Juju  computes the binding itself when no space is provided (depending on spaces available + configurations). 

I know that `juju integrate...` does not have any option to choose which space to bind to, that's a separate command. But I don't believe adding an additional `Bind` resource is necessary.

Thanks for your feedback.

**Comment by hmlanigan** [comment]
@gboutry Thank you for the proposal.

### Regarding the application schema change:

Default Space is a specific concept in juju, I'd rather name the schema key "endpoint-bindings". These bindings can contain a space name and more easily map to the longer term goal in #336.  As well, using a Bindings key also allows for more granularity rather than limiting to a single space for all of the application's endpoints. 

Bindings could be of type `schema.ListNestedBlock` or `schema.ListAttribute`. I'm leaning more to ListNestedBlock to allow  the upcoming space resources to be used easily. The NestedBlock could have a 'space' and 'endpoint' attributes. Only the space being required to indicate the default space for an application's endpoints.

I need to ponder the idea of computed here - they've turned into a big pain point when optional.

### Regarding the integration schema change:

I do not believe it's necessary. 

`juju deploy --bind` can be accomplished by creating a new application resource in your plan including `endpoint-bindings`.

`juju bind <application>` can be accomplished by adding/changing the `endpoint-bindings` within your plan's application resource and re-applying it. 

I'm not sure of what action removing the bindings from your plan will have.

**Comment by gboutry** [comment]
I'm not sure we can just unbind an application. I think the appropriate behavior would be to go back to the default space (I interpret the removal of the block as intent)

Yeah, a schema like the following would meet my needs:

```go
# not sure about dashes in ListNestedBlock
"endpoint_bindings": schema.ListNestedBlock{
	Description: "Configure endpoints bindings",
	NestedObject: schema.NestedBlockObject{
		Attributes: map[string]schema.Attribute{
			"endpoint": schema.StringAttribute{
				Description: "Name of the endpoint to bind to a space.",
				Optional:    true,
			},
			"space": schema.StringAttribute{
				Description: "Name of the space to bind the endpoint to.",
				Required:    true,
			},
		},
	},
	Validators: []validator.List{
		listvalidator.UniqueValues(), // Check if better validator
	},
},
```

This would work fine with my goal, which would look like this:
```tf
resource "juju_application" "my_app" {
...
  endpoint_bindings {
    space = "management"
  }

  endpoint_bindings {
    space    = "public"
    endpoint = "public-endpoint1"
  }
...
}
```

**Comment by gboutry** [comment]
What happens if I do the following:

```tf
resource "juju_application" "app1" {
  endpoint_bindings {
     space    = "private"
     endpoint = "certificates"
  }
}

resourece "juju_application" "app2" {
  endpoint_bindings {
     space    = "public"
     endpoint = "certificates"
  }
}

resource "juju_integration" "app1-to-app2" {
  application {
    name     = "app1"
    endpoint = "certificates"
  }

  application {
    name     = "app2"
    endpoint = "certificates"
  }
}
```

That's why `juju_integration` seemed like a good candidate to me.

**Comment by hmlanigan** [comment]
Specifying an endpoint binding while deploying a charm, is independent of an integration being made. Yes, if you want to integration two endpoints, they should be in the same space.  However running `juju integration` mades no changes to space bindings.

**Comment by hmlanigan** [comment]
> I'm not sure we can just unbind an application. I think the appropriate behavior would be to go back to the default space (I interpret the removal of the block as intent)

Ah, yes, you're correct, you can return all of the bindings to the default-space. We should consider how that looks within a terraform plan. That could be the behavior if the entire endpoint-binding block is removed.

**Comment by hmlanigan** [comment]
I just found this tip "Use [nested attribute types](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/attributes#nested-attribute-types) instead of block types for new schema implementations. Block support is mainly for migrating legacy SDK-based providers.", in the TF docs. 

Looks like we should investigate those nested attribute types, I haven't used them yet. Perhaps "Set Nested Attribute" is appropriate

**Comment by gboutry** [comment]
This is what schema description looks like with ListNestedAttribute:
```go
"endpoint_bindings": schema.ListNestedAttribute{
	Description: "Configure endpoint bindings",
	Optional:    true,
	NestedObject: schema.NestedAttributeObject{
		Attributes: map[string]schema.Attribute{
			"endpoint": schema.StringAttribute{
				Description: "Name of the endpoint to bind to a space.",
				Optional:    true,
			},
			"space": schema.StringAttribute{
				Description: "Name of the space to bind the endpoint to.",
				Required:    true,
			},
		},
	},
	Validators: []validator.List{
		listvalidator.UniqueValues(), // Check if better validator
	},
},
```

And this would look like this in a terraform plan:

```tf
resource "juju_application" "myapp" {
  endpoint_bindings = [
    {
      space = "management" <-- default space
    },
    {
      space    = "internal"
      endpoint = "certificates"
    }
  ]
}
```

(this is based on docs research, not actually tested/written)

**Comment by gboutry** [comment]
@hmlanigan after some prototyping, I believe `SetNestedAttribute` is a better fit for this use case; simply because ordering (and duplicate) values don't matter, and I don't want having to dedup + sort values, while SetNested does it automatically.

The following schema makes more sense to me:
```go
"endpoint_bindings": schema.SetNestedAttribute{
	Description: "Configure endpoint bindings",
	Optional:    true,
	NestedObject: schema.NestedAttributeObject{
		Attributes: map[string]schema.Attribute{
			"endpoint": schema.StringAttribute{
				Description: "Name of the endpoint to bind to a space.",
				Optional:    true,
			},
			"space": schema.StringAttribute{
				Description: "Name of the space to bind the endpoint to.",
				Required:    true,
			},
		},
	},
	Validators: []validator.Set{
		# ensure endpoint is unique across elements
	},
},
```

Endpoint bindings still looks the same from a terraform plan perspective:
```tf
resource "juju_application" "myapp" {
  endpoint_bindings = [
    {
      space = "management" <-- default space
    },
    {
      space    = "internal"
      endpoint = "certificates"
    }
  ]
}
```
