### ISSUE TITLE
Replaced units lose relations

### ISSUE THREAD

**Issue by mthaddon** [juju/terraform-provider-juju#401]
### Description

If the juju terraform provider removes and replaces units/an application, it seems to lose relations. Running `terraform apply` twice adds the relations back in.

### Urgency

Casually reporting

### Terraform Juju Provider version

0.10.1

### Terraform version

v1.7.2-dev

### Terraform Configuration(s)

```terraform
Any configuration where the constraints for an application are changed, and that application has relations.
```

### Reproduce / Test

```shell
1. Deploy an application with relations via terraform.
2. Change its constraints and `terraform apply`
3. See the relations are lost, rerun `terraform apply` to restore relations.
```

### Debug/Panic Output

```shell
See https://pastebin.canonical.com/p/647WGBtMJ7/ (sorry, Canonical only).
```

**Comment by hmlanigan** [comment]
@mthaddon - Due to how the terraform client determines what actions should be taken, it's impossible for the juju provider to recreate the integrations afaik, To avoid this problem, additional terraform directives are required in your plan. Please see the example here:
https://registry.terraform.io/providers/juju/juju/latest/docs/resources/integration

**Comment by jameinel** [comment]
Escalated in the IS Sync.
This is happening when you have 2 applications, with an integration between them. If you change eg memory constraints on one application, terraform rightly notices that it needs to remove and redeploy that application. but while there is an integration resource, it doesn't recreate it (it doesn't realize that removing one of the applications will auto remove the integration).

**Comment by amandahla** [comment]
Should this PR be reverted?
https://github.com/juju/terraform-provider-juju/pull/192

**Comment by jameinel** [comment]
@amandahla I don't think this is related to your PR. We were discussing it in our bug triage, and Heather clarified that the issue is that setting up the right inter-object dependency so that it gets rebuilt isn't possible to be done in the provider code, but needed to be done when the integration is declared by the user. She's going to follow up with more detail.

**Comment by hmlanigan** [comment]
@amandahla,  this issue is unrelated, no need to revert your PR. Thanks for checking.

**Comment by hmlanigan** [comment]
Inside of the terraform provider for juju there is no way to understand that an application has an integration which needs to be replaced if the application is replaced. Due to the schema definition, when the constraints are changed, the provider gets a call to Destroy and Create application, not Update. It doesn't know the difference when Create is called to deploy an application, or when an application  is being replaced.

Running `terraform plan && terraform apply` on the plan a second time works because when terraform interrogates juju to find the integration data to determine if changes are necessary, the integration doesn't exist and it calls Create for the integration.

To avoid calling `terraform plan && terraform apply` a second time, add a lifecycle [meta-argument](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle) of [replace_trigger_by](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by) to the integrate resource. You specify the attributes of the applications referenced in the integration which can cause the application to be destroyed and recreated.

For examples, if the integration is between two applications resources labeled wordpress and percona-cluster, the lifecycle meta-argument would look like:
``` terraform
  lifecycle {
    replace_triggered_by = [
      juju_application.wordpress.name,
      juju_application.wordpress.model,
      juju_application.wordpress.constraints,
      juju_application.wordpress.placement,
      juju_application.wordpress.charm.name,
      juju_application.percona-cluster.name,
      juju_application.percona-cluster.model,
      juju_application.percona-cluster.constraints,
      juju_application.percona-cluster.placement,
      juju_application.percona-cluster.charm.name,
    ]
  }
```

Additional conversation on this topic can be found: https://matrix.to/#/!tGlkJIgTBsNijRGgvq:ubuntu.com/$nK4yzW4xUeY0fjchOjAqG4iVh7C3UAGPQShZc0w0WtY?via=ubuntu.com&via=matrix.org 

We will be adding this detail to the documentation on juju.is as well in the near future.
