### ISSUE TITLE
Add Resources to the Application resource schema

### ISSUE THREAD

**Issue by alesstimec** [juju/terraform-provider-juju#428]
### Type of change

Changing existing schema

### Description

The plan is to add a resources field to the application resource, which would let us specify resource version to be used in the deploy. That way users can explicitly specify resource revisions.

See PR #427.

### Details

I added an optional "resources" field to the application resource.
```
"resources": schema.MapAttribute{
				Description: "Charm resource revisions. Must evaluate to an integer.",
				Optional:    true,
				ElementType: types.Int64Type,
			}
```

**Comment by hmlanigan** [comment]
Thank you for the contribution, it's great to see this bug fixed. 

Adding the ability to specify a resource revision brings some interesting questions. For deploy, or the equivalent of `juju attach-resource is easy enough. 

However what to do with refresh and expectations there? Usually if the charm revision changes, the resource may be updated as well as well to the latest, however if it doesn't change in the plan, terraform will get upset if it is changed. 

What happens if we don't start recording it for any application with a resource (set `Computed: true`), terraform won't know if there is a change. 

Why not use the `ElementType: types.Int64Type`? Otherwise you'll have to add a Validator to ensure the string is really an int.

**Comment by alesstimec** [comment]
Changed type to Int64Type..

**Comment by alesstimec** [comment]
Added to documentation
```
There are a few scenarios that need to be considered:
	* If the plan does not specify resource revision and resources are added to the plan,
	resources with specified revisions will be attached to the application (equivalent
	to juju attach-resource).
	* If the plan does specify resource revisions and:
		* If the charm revision or channel is updated, then resources get updated to the 
		  latest revision.
		* If the charm revision or channel are not updated, then no changes will take 
		  place (juju does not have an "un-attach" command for resources).
```

**Comment by hmlanigan** [comment]
Approved after speaking with @alesstimec. Some changes to the documentation are requested in the PR.
