### ISSUE TITLE
Allow terraform to execute on models which have disable-command all

### ISSUE THREAD

**Issue by dparv** [juju/terraform-provider-juju#483]
### Requirements

```terraform
A usecase for this is when we want to force people to use GitOps approach to modify settings on a juju model and prevent them from using juju XXX commands.

We have noticed that if disable-command all is set on a model terraform can't apply changes.

Not sure if this is for terraform or juju to be able to disable by user.
```

### Urgency

Casually wishlisting

**Comment by cderici** [comment]
@dparv Thanks for bringing to our attention! Though this is about the implementation of the `disable-command` on the Juju side. I need to double check the codes but it sounds like the `disable-command` is blocking the API for all the clients instead of just blocking the juju-cli. Please [file a bug on the LP](https://bugs.launchpad.net/juju/+filebug) so it's fixed on the Juju side.
